name: "InventoryBot"
version: "1.1.4"
slug: "inventorybot"
description: "Barcode scanner inventory management system"
image: ghcr.io/njyjn/inventorybot
startup: services
boot: auto
host_network: true
ingress: false
map:
  - type: share
    read_only: false
options:
  database_url: ""
  port: 3001
schema:
  database_url: "str"
  port: "port"
arch:
  - aarch64